### ISSUE TITLE
Additional info for Writer view

### ISSUE THREAD

**Issue by alexfimerix** [UAMediaProd/lesson-builder#1]
As a SME writing content into Blocks, I require a static view of the Time on Task set for the current block. 

I also require the ability to see the applied Scaffolding for the block when in the Editing Block modal window. This could be present under the content or visible through the click of a tooltip or something similar. 

If possible I would also like to have the pattern type colour present somewhere in the Block Edit window as a visual indicator of what type of activity I am currently writing.

**Comment by huiua** [comment]
Following changes have been made to address this issue.
- Time on Task is now visible in Writer view(both editor popup and preview)
- The activity type name has been added to the writer view (in editor popup). 
- There's an info icon next to the learning pattern. Hovering over the icon for a second, it will show the scaffolding as a tooltip. And the colour of the info icon has been changed to the activity type colour as an indicator.
