### ISSUE TITLE
Searching for lesson titles

### ISSUE THREAD

**Issue by Brattler11** [UAMediaProd/lesson-builder#16]
As a user, I would like a search button to quickly locate the name of a lesson within a module. I should be able to do this based on any keyword which actually belongs in the lesson title. Once located,  I can click and navigate directly to the lesson page.

**Comment by huiua** [comment]
Search bar has been added to the Course Status section in the dashboard. This is for searching keywords in lesson titles, and it's functional when the module filter is applied.
<img width="1222" alt="Screen Shot 2022-05-10 at 10 51 28 am" src="https://user-images.githubusercontent.com/101075316/167523860-d1726831-0246-4628-a096-b0eec6bb7ae8.png">
